function A = linplotscat(a,b,xlab,ylabl,markerspec)   
a(isnan(b)) = []; b(isnan(b)) = []; 

    A = scatter(a,b,75,markerspec,'filled'); hold on
    [r p] = corr(a,b,'Type','Spearman');
    [yCalc ba Rsq] = linregress(a,b);
%     [b1 stats] = robustfit(a,b)
    hold on; plot(a,yCalc,'k-','LineWidth',2)
    xlabel(xlab,'FontSize',13); ylabel(ylabl,'FontSize',16)
    annotation(gcf,'textbox',...
        [0.153 0.119 0.342 0.19],...
        'String',{sprintf('y = %0.3f + %0.3fx',ba),sprintf('R^2 = %0.2f',Rsq),sprintf('P = %0.3f',p(1))},...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12,...
        'FitBoxToText','off'); grid on
    set(gcf,'Position',[733   678   451   420])